### ISSUE TITLE
signac 2.0 post-merge cleanup tasks

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#844]
The following task list was identified during review of #834 / #835.

- [x] Remove `cov.sh`. https://github.com/glotzerlab/signac/pull/834#discussion_r1007412809, #845 
- [x] Remove `deprecation` from `doc/requirements.txt`. https://github.com/glotzerlab/signac/pull/834#discussion_r1007413618, #845 
- [x] See if we can remove `benchmark.py` from the `setup.cfg` pydocstyle exclusions. https://github.com/glotzerlab/signac/pull/834#discussion_r1007414075, #845 
- [x] Refactor `signac/common/config.py`. Only `Config` is public. https://github.com/glotzerlab/signac/pull/834#discussion_r1007416929, #860
- [x] `get_validator` can probably be refactored/removed. https://github.com/glotzerlab/signac/pull/835#discussion_r1011015014, #853 
- [x] Search for remaining `TODO` items and address them. https://github.com/glotzerlab/signac/pull/834#discussion_r1007417808

**Comment by mikemhenry** [comment]
Removing `cov.sh` in https://github.com/glotzerlab/signac/pull/849

**Comment by bdice** [comment]
I resolved the remaining TODO items. See PRs:
- https://github.com/glotzerlab/signac/pull/858
- https://github.com/glotzerlab/signac/pull/859

The only TODO left is one in `signac.testing`, which should be resolved by whatever we do with issue #709.

**Comment by vyasr** [comment]
I'm going to remove the remaining items in the task list of this issue and close it. The updates to other packages/examples/docs is covered by #831.
